### ISSUE TITLE
Process for adding MSFS location manually

### ISSUE THREAD

**Issue by iamrjc** [NathanVaughn/msfs-mod-manager#17]
If the MSFS 2020 installation is not found automatically and the user browses to it, this should be saved upon success in config.ini as the value of the sim_folder key?

Manually can be done by browsing to "%appdata%/Roaming/MSFS Mod Manager" and modifying the config.ini by adding a new line for **sim_folder =** and adding the full path to MSFS e.g. _C:/users/<USERNAME>/AppData/Local/Packages/MS FLIGHT SIM/LocalCache/Packages_   full example:

```
[settings]
theme = None
last_version_check = 2020-09-08 22:38:17
sim_folder = C:\Users\MYNAMEGOESHERE\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages
```

Great utility btw! Thanks for creating.

**Comment by NathanVaughn** [comment]
You're right, thank you. I messed up my logic for that. I'll get a fix out soon.
