### ISSUE TITLE
Type field does not distinguish between Aircraft and Liveries

### ISSUE THREAD

**Issue by russellii** [NathanVaughn/msfs-mod-manager#20]
This is obviously hard to find out, as there seems little consistency in community objects, so may not be possible without lots of phasing.

**Comment by NathanVaughn** [comment]
This is being parsed from the `content_type` field in each mod's `manifest.json` file. I'm not familiar enough with the SDK to know what the acceptable values are, but this is an issue with what the mods provide. Also, if you look at the files for some of the livery mods, they're effectively overwriting specific default aircraft files, so the difference between an aircraft mod and just liveries is pretty small.
