### ISSUE TITLE
Process is not ending itself correctly after launching the installer

### ISSUE THREAD

**Issue by Jimver** [NathanVaughn/msfs-mod-manager#43]
So I first already had 0.5.0 installed, got the update notification for 0.5.1, clicked it and got an error during installation (see screenshot below).

I then uninstalled 0.5.0 via programs and features, and installed 0.5.1 from scratch, but got the same error (see same screenshot below).

UPDATE: Ok, so apparently the program was running but it was not in the taskbar. I don't know how that can happen but I manually ended the process in task manager and now it works! Feel free to close this or make another issue for the taskbar bug (don't know how to reproduce that though).

## Expected Behavior
No error on install/update

## Actual Behavior
Error on install/update
![image](https://user-images.githubusercontent.com/7677699/98690446-3dca2f00-236d-11eb-8aaf-ef074e726428.png)

## Steps to Reproduce the Problem

  1. Download version 0.5.1 installer
  2. Run installer
  3. Get error

## Specifications

  - Application Version: `v0.5.1`
  - MSFS Edition: (MS Store)

## Debug Log Contents (only if reporting a bug)

This file is found at `%APPDATA%\MSFS Mod Manager\debug.log`

(Everything after the last `__main__:<module>:27 - -----------------------` line)

```
debug log
```

**Comment by NathanVaughn** [comment]
Interesting... this seems like the process is not killing itself properly after launching the installer in the [`install_new_version`](https://github.com/NathanVaughn/msfs-mod-manager/blob/5542d7247e5f6644fa16f7a4f36cc4ba06bf3eaf/src/main/python/lib/version.py#L187) function. This sounds like some Qt weirdness potentially. I've never seen this myself, but I'll investigate more thoroughly ending the process after launching the installer.

**Comment by NathanVaughn** [comment]
With all my research, I still don't really know why this occurred. `sys.exit` *should* be pretty forcefully killing the process. I went ahead and tried to make it even more certain. At least the workaround is simple.
