### ISSUE TITLE
symlinks maybe?

### ISSUE THREAD

**Issue by dartvader123** [NathanVaughn/msfs-mod-manager#48]
Hi, 
Thanks for the good job, im trying to manage the Community folder wity a similar Python script (without GUI...) and in my opinion will be better to use symlinks instead of moving folders back and forth. This can cause some trouble if the software crash in the middle of a move operation, and become very slow if you have to enable/disable many GB from one file system to another (like in my case...sic...).
What about adding an option to use symlinks instead of "move", the symlink option need "run as administrator" so maybe someone don't like it.

Thanks

**Comment by NathanVaughn** [comment]
I agree this is a good idea, and I've seen some other mod manager use this method. I'll definitely look into this more.

**Comment by Ircghost** [comment]
Yes, I installed this addon manager hoping that it was a simlink program. Really hope you do implement it, I was looking for an easier way to not manually need to make simlinks.. will also be a lot better for everyone's SSD to not need to write constantly, and from a user perspective, creating simlinks only takes about a second, so you can disable and enable on the fly!

**Comment by NathanVaughn** [comment]
Just an update, I've started work on this. The largest issues are that:
1) True Windows NTFS symlinks require Admin privileges which I want to avoid
2) Directory junctions (which are basically symlinks but only for directories), don't require Admin, but Python lacks real support for them, so implementing them nicely takes a bit of hacky workarounds.

**Comment by NathanVaughn** [comment]
Implemented with [v1.0.0](https://github.com/NathanVaughn/msfs-mod-manager/releases/tag/v1.0.0)
