### ISSUE TITLE
configuration of directory for disabled addons

### ISSUE THREAD

**Issue by schmiko96** [NathanVaughn/msfs-mod-manager#50]
## Expected Behavior
possibility for configuration of directory for the disabled addons

## Actual Behavior
at the moment the app stores the disabled addons at <C:\Users\xxxx\AppData\Roaming\MSFS Mod Manager\modCache>, this could not be changed, but in my case, the system drive C: has not much file space.
It would be great, if it is possible to change that cache directory in the preferences of the mod-manager 

  - Application Version: `v0.5.3`
  - MSFS Edition: MS Store

**Comment by NathanVaughn** [comment]
If you go to the `Edit` menu at the top, you should be able change the directory that disabled mods are kept. In the latest version or two, it should move any existing disabled mods into this directory for you as well. 
![image](https://user-images.githubusercontent.com/8636459/101995298-9c493c80-3c8e-11eb-9ca1-ec961fb8f7ed.png)
